E-COMM_KAMALİ/Areas/Admin/Controllers/UserListController.cs
using ECOMM.Business.Abstract;
using ECOMM.Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ECOMM.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class UserListController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly IRoleService _roleService;
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;

        public UserListController(IRoleService roleService, UserManager<User> userManager, RoleManager<ApplicationRole> roleManager, IUserService userService)
        {
            _roleService = roleService;
            _userManager = userManager;
            _roleManager = roleManager;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var roles = await _roleManager.Roles.ToListAsync();

            foreach (var user in users)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                user.UserRoles = userRoles.Select(role => new ApplicationUserRole
                {
                    Role = roles.FirstOrDefault(r => r.Name == role),
                    UserId = user.Id
                }).ToList();
            }

            ViewBag.AllRoles = roles;
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(string userId, string roleId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var role = await _roleManager.FindByIdAsync(roleId);

            if (user == null || role == null)
            {
                return BadRequest("Kullanıcı veya rol bulunamadı.");
            }

            var currentRoles = await _userManager.GetRolesAsync(user);

            if (currentRoles.Contains(role.Name))
            {
                return BadRequest("Kullanıcı zaten bu role sahiptir.");
            }

            if (currentRoles.Any())
            {
                var oldRole = currentRoles.First();
                await _userManager.RemoveFromRoleAsync(user, oldRole);
            }

            var result = await _userManager.AddToRoleAsync(user, role.Name);
            if (result.Succeeded)
            {
                return Ok("Rol başarıyla atandı.");
            }

            return BadRequest("Rol atama işlemi başarısız oldu.");
        }

        [HttpGet("GetAllRolesAsync")]
        public IActionResult GetAllRolesAsync()
        {
            var roles = _roleManager.Roles.ToList();
            return Json(roles);
        }

        #region GetRoleById
        [HttpGet("GetRoleById")]
        public async Task<IActionResult> GetRoleById([FromQuery] string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
                return BadRequest("Rol ID'si boş veya geçersiz.");

            var role = await _roleService.GetRoleByIdAsync(roleId);

            if (role == null)
                return NotFound("Rol bulunamadı.");

            return Json(role);
        }
        #endregion

        #region Update 
        [HttpPost("UpdateRoleAsync")]
        public async Task<IActionResult> UpdateRoleAsync([FromQuery] string roleId, [FromBody] ApplicationRole model)
        {
            if (roleId == null || model == null)
            {
                return BadRequest("Geçersiz veri.");
            }

            try
            {
                var existingRole = await _roleService.GetRoleByIdAsync(roleId);

                if (existingRole == null)
                {
                    return NotFound("Rol bulunamadı.");
                }

                existingRole.RoleName = model.RoleName;
                existingRole.Description = model.Description;
                existingRole.Name = model.RoleName;
                existingRole.NormalizedName = model.RoleName.ToUpper();

                var result = await _roleService.UpdateRoleAsync(existingRole);

                if (result.Succeeded)
                {
                    return Ok("Rol başarıyla güncellendi.");
                }

                return BadRequest("Rol güncelleme işlemi başarısız oldu.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Sunucu hatası: {ex.Message}");
            }
        }
        #endregion

        #region CreateRole 
        [HttpGet("CreateRole")]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost("CreateRole")]
        public async Task<IActionResult> CreateRole([FromBody] ApplicationRole model)
        {
            if (ModelState.IsValid)
            {
                var role = new ApplicationRole
                {
                    RoleName = model.RoleName,
                    Description = model.Description,
                    Name = model.RoleName,
                    NormalizedName = model.RoleName.ToUpper()
                };

                var result = await _roleService.CreateRoleAsync(role);

                if (result.Succeeded)
                {
                    return Ok("Rol başarıyla oluşturuldu.");
                }

                return BadRequest("Rol oluşturma işlemi başarısız oldu.");
            }

            return BadRequest("Geçersiz veri.");
        }
        #endregion

        #region DeleteRole 
        [HttpPost("DeleteAsyncRoles")]
        public async Task<IActionResult> DeleteAsyncRoles([FromBody] string roleId)
        {
            if (string.IsNullOrEmpty(roleId))
            {
                return BadRequest("Rol ID'si boş olamaz.");
            }

            var result = await _roleService.DeleteRoleAsync(roleId);

            if (result.Succeeded)
            {
                return Ok("Rol başarıyla silindi.");
            }

            return BadRequest("Rol silme işlemi başarısız oldu."); 
        }
        #endregion
    }
}

E-COMM_KAMALİ/Areas/Admin/Views/UserList/CreateRole.cshtml
@{
    ViewData["Title"] = "Admin Rol Ekleme";
}

<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0">Roller</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card bg-light text-dark">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-11">
                                    <box-icon name="tag" color="dark" size="sm" animation="tada"></box-icon> Roller
                                </div>
                                <div class="col-1 text-end">
                                    <a id="btnAdd" href="#" class="btn btn-outline-primary"> Yeni Rol Ekle</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="tblAspNetRoles" class="table table-editable table-nowrap align-middle">
                                    <thead>
                                        <tr>
                                            <th>Rol Adı</th>
                                            <th>Rol Açıklaması</th>
                                            <th>İşlemler</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" role="dialog" aria-labelledby="modalTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <input type="hidden" id="roleId" />

            <div class="modal-body">
                <div class="mb-3 row">
                    <label class="form-label">Rol Adı: </label>
                    <input type="text" id="roleName" placeholder="Lütfen Rol Adı giriniz" class="form-control" required />
                    <span id="roleName-error" style="color:red; display:none;">Rol Adı alanı boş bırakılamaz.</span>
                </div>
                <div class="mb-3 row">
                    <label class="form-label">Rol Açıklaması: </label>
                    <input type="text" id="description" placeholder="Lütfen Rol Açıklamasını giriniz" class="form-control" required />
                    <span id="description-error" style="color:red; display:none;">Alan boş bırakılamaz.</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button type="button" id="btnSave" class="btn btn-primary">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
          
            var table = $('#tblAspNetRoles').DataTable({
                ajax: {
                    url: '/Admin/UserList/GetAllRolesAsync', 
                    dataSrc: '',
                    error: function (xhr, error, thrown) {
                        console.error('Ajax Error', error, thrown);
                        Swal.fire('Error', 'Error loading roles', 'error');
                    }
                },
                columns: [
                    { data: 'roleName', title: 'Rol Adı' },
                    { data: 'description', title: 'Rol Açıklaması' },
                    {
                        data: null,
                        title: 'İşlemler',
                        render: function (data, type, row) {
                            return `
                                                        <a href="#" class="btn btn-sm btn-warning editRole" data-id="${row.id}">Düzenle</a>
                                                        <a href="#" class="btn btn-sm btn-danger deleteRole" data-id="${row.id}">Sil</a>
                                                    `;
                        }
                    }
                ]
            });

        
            $('#btnAdd').on('click', function () {
                $('#modalTitle').text("Yeni Rol Ekle");
                $('#roleId').val("");
                $('#roleName').val("");
                $('#description').val("");
                $('#modal').modal('show');
            });

            
            $(document).on('click', '#btnSave', function () {
                var roleId = $('#roleId').val();
                var roleName = $('#roleName').val();
                var description = $('#description').val();

              
                if (roleName.trim() === "") {
                    $('#roleName-error').show();
                    return;
                } else {
                    $('#roleName-error').hide();
                }
                if (description.trim() === "") {
                    $('#description-error').show();
                    return;
                } else {
                    $('#description-error').hide();
                }
               
                var ajaxUrl = roleId === "" ? "/Admin/UserList/CreateRole" : "/Admin/UserList/UpdateRoleAsync?roleId="+roleId;
                var requestData = JSON.stringify({
                    
                   roleName: roleName,
                    description: description
                });

            
                $.ajax({
                    type: "POST",
                    url: ajaxUrl,
                    contentType: 'application/json',
                     data: requestData,
                    success: function (response) {
                        $('#modal').modal('hide');
                        $('#tblAspNetRoles').DataTable().ajax.reload(); 
                        Swal.fire('Başarılı', roleId === "" ? 'Rol başarıyla eklendi' : 'Rol başarıyla güncellendi', 'success');
                    },
                    error: function () {
                        Swal.fire('Hata', 'İstek işlenirken hata oluştu', 'error');
                    }
                });
            });

        
            $(document).on('click', '.editRole', function () {
                var roleId = $(this).data('id');
              
              
                $.ajax({
                    type: "GET",
                    url: "/Admin/UserList/GetRoleById?roleId="+roleId,
                   
                    success: function (role) {
                        $('#modalTitle').text("Düzenle Rol");
                        $('#roleId').val(role.id);
                        $('#roleName').val(role.roleName);
                        $('#description').val(role.description);
                        $('#modal').modal('show');
                    },
                    error: function () {
                        Swal.fire('Hata', 'Rol verilerini getirirken hata oluştu', 'error');
                    }
                });
            });
          
            
            $(document).on('click', '.deleteRole', function () {
                var roleId = $(this).data('id');
               
                Swal.fire({
                    title: 'Emin misiniz?',
                    text: "Bu işlem geri alınamaz!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Evet, sil!',
                    cancelButtonText: 'Hayır, iptal et'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // AJAX ile silme işlemi
                        $.ajax({
                            type: "POST",
                            url: "/Admin/UserList/DeleteAsyncRoles", // Doğru URL
                            contentType: 'application/json',
                            data: JSON.stringify(roleId),
                            success: function (response) {
                                $('#tblAspNetRoles').DataTable().ajax.reload(); // Güncellenmiş tablo ID'si
                                Swal.fire('Silindi!', 'Rol başarıyla silindi.', 'success');
                            },
                            error: function () {
                                Swal.fire('Hata', 'Rol silinirken hata oluştu', 'error');
                            }
                        });
                    }
                });
            });
        });

    </script>
}





























@* @model Blog.Core.Models.ApplicationRole

<h2>Create Role</h2>

<form asp-action="CreateRole" method="post">
    <div class="form-group">
        <label asp-for="RoleName">Role Name</label>
        <input asp-for="RoleName" class="form-control" />
        <span asp-validation-for="RoleName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create Role</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
 *@

E-COMM_KAMALİ/Areas/Admin/Views/UserList/Index.cshtml
@using ECOMM.Core.Models;
@model List<User>

@{
    ViewData["Title"] = "Kullanıcı Listesi";
    var allRoles = ViewBag.AllRoles as List<ApplicationRole>; 
}

<h2>Kullanıcı Listesi</h2>

<table class="table" style="width: 100%;">
    <thead>
        <tr>
            <th>Kullanıcı Adı</th>
            <th>Email</th>
            <th>Telefon Numarası</th>
            <th>Mevcut Roller</th>
            <th>Yeni Rol Atama</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>@user.PhoneNumber</td>
                <td>@string.Join(", ", user.UserRoles.Select(ur => ur.Role?.RoleName))</td> 
                <td>
                    <select class="form-control" id="roleSelect_@user.Id" onchange="assignRole('@user.Id', this.value)">
                        <option value="">Rol Seç</option>
                        @foreach (var role in allRoles)
                        {
                            <option value="@role.Id">@role.RoleName</option>
                        }
                    </select>
                </td>
                <td>
                  @*   <a href="@Url.Action("Details", new { id = user.Id })" class="btn btn-info">Detaylar</a> *@
                    <a href="@Url.Action("Edit", new { id = user.Id })" class="btn btn-warning">Düzenle</a>
                    <a href="@Url.Action("Delete", new { id = user.Id })" class="btn btn-danger">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Css{
    <style>
        .table {
            width: 100%; /* Tablonun tüm genişliği kaplaması için */
            max-width: 100%; /* Maksimum genişlik */
            border-collapse: collapse; /* Kenar çakışmalarını önlemek için */
        }

            .table th, .table td {
                padding: 15px; /* Hücre içi boşluk */
                text-align: left; /* Metin hizalaması */
                border: 1px solid #ddd; /* Kenarlık */
            }

            .table th {
                background-color: #f2f2f2; /* Başlık hücreleri için arka plan rengi */
            }
    </style>

}

@section Scripts {
    <script type="text/javascript">
        function assignRole(userId, roleId) {
            $.ajax({
                url: '@Url.Action("AssignRole", "UserList")',
                type: 'POST',
                data: {
                    userId: userId,
                    roleId: roleId
                },
                success: function (response) {
                
                    const currentRoles = @Html.Raw(Json.Serialize(Model.Select(u => u.UserRoles.Select(ur => ur.Role.Name).ToList()).ToList()));

                 
                    if (response === "Rol başarıyla atandı.") {
                      
                        if (currentRoles.includes('Admin')) {
                            Swal.fire({
                                icon: 'warning',
                                title: 'Uyarı',
                                text: 'Kullanıcı zaten admin rolüne sahip!',
                            });
                        } else {
                          
                            Swal.fire({
                                icon: 'success',
                                title: 'Başarılı',
                                text: 'Rol başarıyla atandı.',
                            });
                        }
                    } else {
                       
                        Swal.fire({
                            icon: 'error',
                            title: 'Hata',
                            text: response,
                        });
                    }
                },
                error: function (error) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Başarısız',
                        text: 'Rol atama başarısız.',
                    });
                }
            });
        }
    </script>
}